name: up_down
description: "A new Flutter project."
publish_to: 'none' # Evita que se publique accidentalmente en pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Iconos estilo iOS
  cupertino_icons: ^1.0.8

  # Paquete para gráficos (barras, circulares, etc.)
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Buenas prácticas de linting
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
