// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwFdW62e5_1X7_h0SGkCQO9PLIxkQHvh4',
    appId: '1:373335188071:web:4105e1ea2a5140bba66ac2',
    messagingSenderId: '373335188071',
    projectId: 'updown-9f356',
    authDomain: 'updown-9f356.firebaseapp.com',
    storageBucket: 'updown-9f356.firebasestorage.app',
    measurementId: 'G-5E9S8PBNS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6rPm2Ko-ol7-fRU0kemMviYWrHBs0Ucw',
    appId: '1:373335188071:android:227c329821ae8024a66ac2',
    messagingSenderId: '373335188071',
    projectId: 'updown-9f356',
    storageBucket: 'updown-9f356.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMnvKegXM5BFekDGaBo2fG-dSPgYiaHaQ',
    appId: '1:373335188071:ios:1c6bfa04834f2746a66ac2',
    messagingSenderId: '373335188071',
    projectId: 'updown-9f356',
    storageBucket: 'updown-9f356.firebasestorage.app',
    iosBundleId: 'com.example.upDown',
  );
}
